dots_and_boxes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('game/', include(('game.urls', 'game'), namespace='game')),
    path('', login_required(TemplateView.as_view(template_name='home.html')), name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import TemplateView

from .views import create_room_view, join_room_view, room_view, pve_room_view, create_pve_room

urlpatterns = [
    path('pvp/', login_required(TemplateView.as_view(template_name='game/pvp.html')), name='two-player'),
    path('pve/', create_pve_room, name='single-player'),
    path('pve/room/<int:room_id>/', pve_room_view, name='pve-room'),
    path('room/create/', create_room_view, name='create-room'),
    path('room/join/', join_room_view, name='join-room'),
    path('room/<int:room_id>/', room_view, name='room'),
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import authentication_view, login_view, signup_view, ProfileUpdateView, game_history_view

urlpatterns = [
    path('', ProfileUpdateView.as_view(), name='profile'),
    path('history/', game_history_view, name='history'),
    path('auth/', authentication_view, name='auth'),
    path('signup/', signup_view, name='sign-up'),
    path('login/', login_view, name='log-in'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='log-out'),
]

user/models.py
from PIL import Image
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.db import models


class CustomUserManager(BaseUserManager):
    def create_user(self, username, password, **other_fields):
        user = self.model(username=username, **other_fields)
        user.set_password(password)

        user.save()
        return user

    def create_superuser(self, username, password, **other_fields):
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)

        return self.create_user(username, password, **other_fields)


class User(AbstractBaseUser, PermissionsMixin):
    avatar = models.ImageField(default='avatar/default.png', upload_to='avatar/')
    username = models.CharField(max_length=127, unique=True)
    email = models.EmailField(max_length=255, unique=True, null=True, blank=True)
    first_name = models.CharField(max_length=127, blank=True, null=True)
    last_name = models.CharField(max_length=127, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.avatar:
            avatar_path = self.avatar.path
            with Image.open(avatar_path) as img:
                # Ensure the image is a square
                width, height = img.size
                if width != height:
                    # Crop the image to a square
                    new_dimension = min(width, height)
                    left = (width - new_dimension) / 2
                    top = (height - new_dimension) / 2
                    right = (width + new_dimension) / 2
                    bottom = (height + new_dimension) / 2
                    img = img.crop((left, top, right, bottom))

                img.save(avatar_path)

    def __str__(self):
        return f"@{self.username}"

user/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms

User = get_user_model()


class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['avatar'].widget.attrs['class'] = 'form-control mb-2'
        self.fields['avatar'].widget.attrs['placeholder'] = 'upload your profile picture'

        self.fields['username'].widget.attrs['class'] = 'form-control mb-2'
        self.fields['username'].widget.attrs['placeholder'] = 'Choose a username'

        self.fields['email'].widget.attrs['class'] = 'form-control mb-2'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter your email (optional)'

        self.fields['first_name'].widget.attrs['class'] = 'form-control mb-2'
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter your first name (optional)'

        self.fields['last_name'].widget.attrs['class'] = 'form-control mb-2'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter your last name (optional)'

        self.fields['password1'].widget.attrs['class'] = 'form-control mb-2'
        self.fields['password1'].widget.attrs['placeholder'] = 'Enter a password'

        self.fields['password2'].widget.attrs['class'] = 'form-control mb-2'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm your password'

    class Meta:
        model = User
        fields = ('avatar', 'username', 'email', 'first_name', 'last_name', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control mb-2'
        self.fields['username'].widget.attrs['placeholder'] = 'Username'

        self.fields['password'].widget.attrs['class'] = 'form-control mb-2'
        self.fields['password'].widget.attrs['placeholder'] = 'Password'


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('avatar', 'username', 'email', 'first_name', 'last_name')

user/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import redirect, render
from django.contrib.auth import login, authenticate, get_user_model
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView

from game.models import Board
from user.forms import SignupForm, LoginForm, ProfileForm


User = get_user_model()


def login_view(request):
    if request.method == 'POST':
        login_form = LoginForm(request, data=request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('home')
    else:
        login_form = LoginForm()

    signup_form = SignupForm()
    context = {
        'title': 'Authentication',
        'signup_form': signup_form,
        'login_form': login_form
    }
    return render(request, 'user/authenticataion-page.html', context=context)


def signup_view(request):
    if request.method == 'POST':
        signup_form = SignupForm(request.POST, request.FILES)
        if signup_form.is_valid():
            signup_form.save()
            messages.success(request, 'Your account has been created!')

            username = signup_form.cleaned_data['username']
            raw_password = signup_form.cleaned_data['password1']
            user = authenticate(request, username=username, password=raw_password)
            if user is not None:
                login(request, user)
                return redirect('home')
        else:
            messages.error(request, 'Authentication failed. Please try logging in manually.')
    else:
        signup_form = SignupForm()

    login_form = LoginForm()
    context = {
        'title': 'Authentication',
        'signup_form': signup_form,
        'login_form': login_form
    }
    return render(request, 'user/authenticataion-page.html', context=context)


def authentication_view(request):
    signup_form = SignupForm()
    login_form = LoginForm()
    context = {
        'title': 'Authentication',
        'signup_form': signup_form,
        'login_form': login_form
    }
    return render(request, 'user/authenticataion-page.html', context=context)


@method_decorator(login_required, name='dispatch')
class ProfileUpdateView(UpdateView):
    model = User
    form_class = ProfileForm
    template_name = 'user/profile.html'
    success_url = reverse_lazy('user:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        form.instance = self.request.user

        if 'avatar' in form.files:
            form.instance.avatar = form.files['avatar']

        return super().form_valid(form)


@login_required
def game_history_view(request):
    user = request.user
    context = {
        'user': user,
        'games': Board.objects.filter(Q(host=user) | Q(guest=user), winner__isnull=False).order_by('-created_at')
    }
    return render(request, 'user/history.html', context=context)

user/templates/user/authenticataion-page.html
{% extends 'base.html' %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block main %}
    <main>
        <section>
            <h2>Sign-up Form</h2>
            <div class="line"></div>

            <form action="{% url 'user:sign-up' %}" method="POST" class="sign-up-form" enctype="multipart/form-data">
                {% csrf_token %}
                {{ signup_form.as_p }}
                <button class="btn" type="submit">Sign-Up</button>
            </form>
        </section>

        <section>
            <h2>Log-in Form</h2>
            <div class="line"></div>

            <form action="{% url 'user:log-in' %}" method="POST" class="log-in-form">
                {% csrf_token %}
                {{ login_form.as_p }}
                <button class="btn" type="submit">Log-In</button>
            </form>

        </section>
    </main>
{% endblock main %}

user/templates/user/history.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <style>
        main {
            display: flex;
            flex-direction: column;
        }

        .games {
            display: flex;
            flex-direction: column;
            gap: 1rem;

        }

        .game {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
            border-radius: 500px;
        }

        .lose {
            background-color: #ff2f2f;
        }

        .win {
            background-color: #007BFF;
        }

        .profile {
            display: flex;
            align-items: center;
            gap: 1rem;
        }

        @media (min-width: 901px) {
            main {
                padding: 50px 150px;
            }
        }

    </style>
{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block main %}
    <main>
        <section>
            <h2>Game History</h2>
            <div class="line"></div>

            <ul class="games m-0 p-0 pt-5">
                {% for board in games %}
                <li class="game m-0 {% if board.winner == request.user %}win{% else %}lose{% endif %}">
                    <div class="profile host-profile">
                        <img src="{{ board.host.avatar.url }}" class="host-avatar rounded-circle" alt="host-avatar" width="50px" height="50px">
                        <div class="username host-username">{{ board.host }}</div>
                    </div>

                    <h4 class="game-result">{{ board.host_score }} | {{ board.guest_score }}</h4>

                    <div class="profile guest-profile">
                        <div class="username guest-username">{{ board.guest }}</div>
                        <img src="{{ board.guest.avatar.url }}" class="guest-avatar rounded-circle" alt="guest-avatar" width="50px" height="50px">
                    </div>
                </li>
                {% endfor %}
            </ul>
        </section>
    </main>
{% endblock main %}

user/templates/user/profile.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.min.js"></script>

<style>
    main {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: flex-start;
        height: 100%;
        padding: 0;
        margin-top: 20rem;
        gap: 0;
        color: black;
    }

    #profile-section {
        width: 100%;
        height: 100%;
        background-color: white;
        padding: 0 10rem;
    }

    #profile-header {
        display: flex;
        justify-content: flex-start;
    }

    #user-avatar {
        position: relative;
        top: -50px;
        background-color: black;
        border-radius: 50%;
        border: 0.5rem solid white;
        box-sizing: content-box;
    }

    #icon-upload-avatar {
        color: black;
        position: relative;
        left: -30px;
        top: 0;
        cursor: pointer;
    }

    #fields {
        display: grid;
        grid-template-columns: repeat(2, minmax(0, 1fr));;
        gap: 2rem;
    }

    .field {
        display: flex;
        flex-direction: column;
    }

    .field input {
        border-bottom: 1px solid black;
    }

    #enable-edit {
        cursor: pointer;
        color: #007BFF;
        text-decoration: underline;
    }

    .buttons {
        display: flex;
        gap: 1rem;
    }

    .btn:hover {
        color: white;
    }

    #cancel-btn {
        background-color: #fff;
        color: #dc3545;
        border: 2px solid #dc3545;
    }

    #cancel-btn:hover {
        color: white;
        background-color: #dc3545;
    }

    #cancel-btn {
        min-width: 15%;
    }

    @media (max-width: 900px) {
        #profile-section {
            padding: 0 2rem 5rem 2rem;
        }

        #fields {
            display: flex;
            flex-direction: column;
        }
    }

</style>
{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block main %}
    <main>
        <section id="profile-section">
            <form method="post" class="m-0" enctype="multipart/form-data">
                <div id="profile-header">
                    <div id="img-wrapper">
                        <img id="user-avatar" width="100" height="100" src="{{ form.instance.avatar.url }}" alt="Profile Picture">
                        <input type="file" name="{{ form.avatar.name }}" accept="image/*" id="id_avatar" hidden>
                        <label id="icon-upload-avatar" for="id_avatar">
                            <img width="20" src="{% static 'img/upload-avatar.svg' %}" alt="upload">
                        </label>
                    </div>
                    <div id="username" class="mt-3">
                        <h3 class="mb-0">{{ user.username }}</h3>
                        <p id="enable-edit" onclick="enable_edit()">Edit Profile</p>
                    </div>
                </div>

                <h2 class="text-start text-secondary mb-3">Personal Information</h2>
                {% for field in form %}
                        {{ field.errors }}
                {% endfor %}

                {% csrf_token %}
                <div id="fields">
                    {% for field in form %}
                        {% if field != form.avatar %}
                            <div class="field">
                                {{ field.label }}
                                {{ field }}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="buttons">
                    <button id="submit-btn" type="submit" class="btn btn-primary">Save Changes</button>
                    <div onclick="window.location.reload()" id="cancel-btn" class="btn btn-danger d-inline-block">Cancel</div>
                </div>
            </form>
        </section>

        <section>

        </section>
    </main>
{% endblock main %}

{% block scripts %}
<script>
    document.querySelector('header div').style.visibility = 'hidden';
</script>

<script>
    const image = document.getElementById("icon-upload-avatar");
    const fields = document.getElementsByClassName("field");
    const submitButton = document.getElementById("submit-btn")
    const cancelButton = document.getElementById("cancel-btn")

    function enable_edit() {
        cancelButton.style.visibility = 'visible';
        submitButton.disabled = false;
        image.setAttribute("for", "id_avatar");
        image.style.cursor = 'pointer';
        image.style.visibility = 'visible';
        for (let field of fields) {
            const input = field.querySelector("input");
            input.disabled = false;
        }
        document.getElementById("enable-edit").style.visibility = 'hidden';
    }

    function disable_edit() {
        cancelButton.style.visibility = 'hidden';
        submitButton.disabled = true;
        image.removeAttribute("for");
        image.style.visibility = 'hidden';
        image.style.cursor = 'unset';
        for (let field of fields) {
            const input = field.querySelector("input");
            input.disabled = true;
        }
    }

    disable_edit()
</script>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const avatarInput = document.getElementById('id_avatar');
        const avatarPreview = document.getElementById('user-avatar');

        avatarInput.addEventListener('change', function(event) {
            const file = event.target.files[0];
            if (file) {
                const reader = new FileReader();
                reader.onload = function(e) {
                    avatarPreview.src = e.target.result;
                    avatarPreview.style.objectFit = 'cover';
                }
                reader.readAsDataURL(file);
            }
        });
    });
</script>
{% endblock %}