dots_and_boxes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('game/', include(('game.urls', 'game'), namespace='game')),
    path('', login_required(TemplateView.as_view(template_name='home.html')), name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import TemplateView

from .views import create_room_view, join_room_view, room_view, pve_room_view, create_pve_room

urlpatterns = [
    path('pvp/', login_required(TemplateView.as_view(template_name='game/pvp.html')), name='two-player'),
    path('pve/', create_pve_room, name='single-player'),
    path('pve/room/<int:room_id>/', pve_room_view, name='pve-room'),
    path('room/create/', create_room_view, name='create-room'),
    path('room/join/', join_room_view, name='join-room'),
    path('room/<int:room_id>/', room_view, name='room'),
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import authentication_view, login_view, signup_view, ProfileUpdateView, game_history_view

urlpatterns = [
    path('', ProfileUpdateView.as_view(), name='profile'),
    path('history/', game_history_view, name='history'),
    path('auth/', authentication_view, name='auth'),
    path('signup/', signup_view, name='sign-up'),
    path('login/', login_view, name='log-in'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='log-out'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Dots & Boxes</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
        <link href='https://fonts.googleapis.com/css?family=Inter' rel='stylesheet'>
        {% load bootstrap5 %}
        {% bootstrap_css %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        {% block styles %}{% endblock %}
    </head>
    <body>
        {% block header %}{% endblock %}
        {% block main %}{% endblock %}
        {% block footer %}{% endblock %}
        {% block scripts %}{% endblock %}
        {% bootstrap_javascript %}
    </body>
</html>

templates/header.html
{% load static %}
<header>
    <a href="{% url 'home' %}" style="all: unset; cursor: pointer"><h1>
        <span><img src="{% static "img/logo.svg" %}" alt=""></span>
        Dots & Boxes
    </h1></a>
    {% if user.is_authenticated %}
        <div id="options" style="display: flex; align-items: center">
            <form style="margin: 0" method="POST" action="{% url 'user:log-out' %}">
                {% csrf_token %}
                <button type="submit" class="logout">
                    <span><img width="25px" height="25px" src="{% static "img/logout.svg" %}" alt="logout"></span> Log out
                </button>
            </form>
            <a id="history" href="{% url "user:history" %}" style="color: white">
                <svg xmlns="http://www.w3.org/2000/svg" width="25px" height="25px" viewBox="0 0 24 24"><path fill="currentColor" d="M9.197 10a.75.75 0 0 0 0 1.5h6.5a.75.75 0 0 0 0-1.5zm-2.382 4a.75.75 0 0 0 0 1.5h6.5a.75.75 0 0 0 0-1.5zm-1.581 4a.75.75 0 0 0 0 1.5h6.5a.75.75 0 0 0 0-1.5z"/><path fill="currentColor" d="M4.125 0h15.75a4.1 4.1 0 0 1 2.92 1.205A4.1 4.1 0 0 1 24 4.125c0 1.384-.476 2.794-1.128 4.16c-.652 1.365-1.515 2.757-2.352 4.104l-.008.013c-.849 1.368-1.669 2.691-2.28 3.97c-.614 1.283-.982 2.45-.982 3.503a2.625 2.625 0 1 0 4.083-2.183a.75.75 0 1 1 .834-1.247A4.126 4.126 0 0 1 19.875 24H4.5a4.125 4.125 0 0 1-4.125-4.125c0-2.234 1.258-4.656 2.59-6.902c.348-.586.702-1.162 1.05-1.728c.8-1.304 1.567-2.553 2.144-3.738H3.39c-.823 0-1.886-.193-2.567-1.035A3.65 3.65 0 0 1 0 4.125A4.125 4.125 0 0 1 4.125 0M15.75 19.875c0-1.38.476-2.786 1.128-4.15c.649-1.358 1.509-2.743 2.343-4.086l.017-.028c.849-1.367 1.669-2.692 2.28-3.972c.614-1.285.982-2.457.982-3.514A2.615 2.615 0 0 0 19.875 1.5a2.625 2.625 0 0 0-2.625 2.625c0 .865.421 1.509 1.167 2.009A.75.75 0 0 1 18 7.507H7.812c-.65 1.483-1.624 3.069-2.577 4.619c-.334.544-.666 1.083-.98 1.612c-1.355 2.287-2.38 4.371-2.38 6.137A2.625 2.625 0 0 0 4.5 22.5h12.193a4.1 4.1 0 0 1-.943-2.625M1.5 4.125c-.01.511.163 1.008.487 1.403c.254.313.74.479 1.402.479h12.86a3.65 3.65 0 0 1-.499-1.882a4.1 4.1 0 0 1 .943-2.625H4.125A2.625 2.625 0 0 0 1.5 4.125"/></svg>
            </a>
            <a href="{% url "user:profile" %}">
                <img
                        class="rounded-circle"
                        src="{{ user.avatar.url }}"
                        alt="profile"
                        width="50px"
                        height="50px"
                >
            </a>
        </div>
    {% endif %}
</header>

templates/home.html
{% extends 'base.html' %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block styles %}
    <style>
        main {
            display: block;
            text-align: center;
        }

        .game-btn {
            background-color: rgba(255, 255, 255, 0.1);
            border: 3px solid white;
            border-radius: 10px;
            color: white;
            width: 50%;
            font-weight: bold;
            font-size: 24px;
        }

        .game-btn:hover {
            background-color: white;
            color: #2473D0;
        }
    </style>
{% endblock %}

{% block main %}
    <main>
        <section>
            <a href="{% url "game:single-player" %}">
                <button class="btn game-btn"><i class="bi bi-robot"></i> Single Player</button>
            </a>

            <a href="{% url "game:two-player" %}">
                <button class="btn game-btn"><i class="bi bi-people-fill"></i> Two Player</button>
            </a>
        </section>
    </main>
{% endblock %}