dots_and_boxes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('game/', include(('game.urls', 'game'), namespace='game')),
    path('', login_required(TemplateView.as_view(template_name='home.html')), name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import TemplateView

from .views import create_room_view, join_room_view, room_view, pve_room_view, create_pve_room

urlpatterns = [
    path('pvp/', login_required(TemplateView.as_view(template_name='game/pvp.html')), name='two-player'),
    path('pve/', create_pve_room, name='single-player'),
    path('pve/room/<int:room_id>/', pve_room_view, name='pve-room'),
    path('room/create/', create_room_view, name='create-room'),
    path('room/join/', join_room_view, name='join-room'),
    path('room/<int:room_id>/', room_view, name='room'),
]

game/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone

User = get_user_model()


class Board(models.Model):
    PLAYER_CHOICES = [
        ('host', 'Host'),
        ('guest', 'Guest'),
    ]

    size = models.IntegerField()
    host = models.ForeignKey(User, on_delete=models.CASCADE, related_name='host_games', null=True, blank=True)
    guest = models.ForeignKey(User, on_delete=models.CASCADE, related_name='guest_games', null=True, blank=True)
    turn = models.CharField(max_length=7, choices=PLAYER_CHOICES, default='host')
    host_score = models.PositiveIntegerField(default=0, null=True, blank=True)
    guest_score = models.PositiveIntegerField(default=0, null=True, blank=True)
    winner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='victories')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Board {self.id} ({self.size}x{self.size})"

    @property
    def is_complete(self):
        scores = {
            self.host: 0,
            self.guest: 0,
        }

        for square in self.squares.all():
            if not square.is_complete:
                return False
            scores[square.winner] += 1

        self.host_score = scores[self.host]
        self.guest_score = scores[self.guest]

        if scores[self.host] > scores[self.guest]:
            self.winner = self.host
            self.save()
            return str(self.host)

        self.winner = self.guest
        self.save()

        return str(self.guest)


class Square(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='squares')
    row = models.IntegerField()
    col = models.IntegerField()
    top = models.BooleanField(default=False)
    left = models.BooleanField(default=False)
    right = models.BooleanField(default=False)
    bottom = models.BooleanField(default=False)
    winner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='won_squares')
    completed_at = models.DateTimeField(blank=True, null=True)

    @property
    def is_complete(self) -> bool:
        is_complete = self.top and self.right and self.bottom and self.left

        if is_complete and self.completed_at is None:
            self.completed_at = timezone.now()
            self.save()

        return is_complete

    class Meta:
        unique_together = ('board', 'row', 'col')

    def __str__(self):
        return f"Square ({self.row}, {self.col}) on Board {self.board.id}"


class GameRoom(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('playing', 'Playing'),
        ('complete', 'Complete'),
    ]

    board = models.OneToOneField(Board, on_delete=models.CASCADE, related_name='game_room')
    player1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='player1_games', null=True, blank=True)
    player2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='player2_games', null=True, blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')
    online_users = models.ManyToManyField(User, related_name='online_in_groups', blank=True)

    def __str__(self):
        return f"GameRoom {self.id} - {self.status}"

    @property
    def is_full(self) -> bool:
        return self.player1 and self.player2

    def add_player(self, player):
        if self.player1 is None:
            self.player1 = player
            self.save()

        elif self.player2 is None and self.player1 != player:
            self.player2 = player
            self.status = 'playing'
            self.save()

game/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import GameRoom, Board, Square


User = get_user_model()


@login_required
def create_room_view(request):
    if request.method == 'POST':
        board_size = int(request.POST.get('board-size'))
        board = Board.objects.create(size=board_size)

        for i in range(1, board_size):
            for j in range(1, board_size):
                Square.objects.create(board=board, row=i, col=j)

        game_room = GameRoom.objects.create(board=board, player1=request.user)
        return redirect('game:room', room_id=game_room.id)

    return render(request, 'game/create_room.html')


@login_required
def join_room_view(request):
    if request.method == 'POST':
        room_id = request.POST['room_id']

        if not GameRoom.objects.filter(id=room_id).exists():
            return render(request, 'game/join_room.html', {'error': f'Room {room_id} doesn\'t exists!'})

        room = GameRoom.objects.get(id=room_id)

        if request.user not in [room.player1, room.player2]:
            if room.is_full:
                return render(request, 'game/join_room.html', {'error': 'Room is full'})
            else:
                room.add_player(request.user)

        return redirect('game:room', room_id=room_id)

    return render(request, 'game/join_room.html')


@login_required
def room_view(request, room_id):
    room = get_object_or_404(GameRoom, id=room_id)

    if request.user not in [room.player1, room.player2]:
        return redirect('game:join-room')

    context = {
        'room_id': room_id,
        'username': request.user.username,
        'board_size': room.board.size,
    }

    return render(request, 'game/pvp-room.html', context)


@login_required
def create_pve_room(request):
    if request.method == 'POST':
        player = request.user
        bot = User.objects.get(username='bot')
        board_size = int(request.POST.get('board-size'))
        board = Board.objects.create(size=board_size, host=player, guest=bot)

        for i in range(1, board_size):
            for j in range(1, board_size):
                Square.objects.create(board=board, row=i, col=j)

        room = GameRoom.objects.create(player1=player, player2=bot, board=board)
        return redirect('game:pve-room', room_id=room.id)

    return render(request, 'game/pve.html')


@login_required
def pve_room_view(request, room_id):
    room = get_object_or_404(GameRoom, id=room_id)

    if request.user != room.player1:
        return redirect('home')

    context = {
        'room_id': room_id,
        'user': request.user,
        'bot': room.player2,
        'board_size': room.board.size,
    }

    return render(request, 'game/pve-room.html', context)

game/templates/game/create_join.html
{% extends 'base.html' %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block styles %}
    <style>
        main {
            display: block;
            text-align: center;
        }

        .game-btn {
            background-color: rgba(255, 255, 255, 0.1);
            border: 3px solid white;
            border-radius: 10px;
            color: white;
            width: 50%;
            font-weight: bold;
            font-size: 24px;
        }

        .game-btn:hover {
            background-color: white;
            color: #2473D0;
        }
    </style>
{% endblock %}

{% block main %}
    <main>
        <section>
            <a href="{% url "game:create-room" %}">
                <button class="btn game-btn">Create Room</button>
            </a>
            <a href="{% url "game:join-room" %}">
                <button class="btn game-btn">Join Room</button>
            </a>
        </section>
    </main>
{% endblock %}

game/templates/game/create_room.html
{% extends 'base.html' %}

{% block styles %}
    <style>
        .game-btn {
            background-color: rgba(255, 255, 255, 0.1);
            border: 3px solid white;
            border-radius: 10px;
            color: white;
            width: 100%;
            margin: 0;
        }

        .game-btn:hover {
            background-color: white;
            color: #2473D0;
        }

        main {
            display: flex;
            justify-content: center;
        }

        section {
            display: flex;
            flex-direction: column;
            text-align: center;
            gap: 10px;
            width: 50%;
        }

        input {
            width: 100%;
            margin: 0;
        }

        .my-row {
            display: flex;
            gap: 10px;
        }

        .my-button {
            position: relative;
            display: flex;
            align-items: center;
            justify-content: center;
            line-height: 250%;
        }

        .my-button label,
        .my-button input {
            position: absolute;
            cursor: pointer;

            z-index: 90;
            height: 100%;
            width: 100%;
        }

        .my-button input[type="radio"] {
            opacity: 0.001;
            z-index: 100;
        }

        .my-button input[type="radio"]:checked + label {
            background-color: white;
            color: #2473D0;
        }

        .game-btn:hover {
            background-color: inherit;
            color: white;
        }


    </style>
{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block main %}
    <main>
        <section>
            <h2>Game Configuration</h2>

            <form method="POST">
                {% csrf_token %}
                <div class="my-row">
                    <p>Board</p>
                    <div class="my-button game-btn">
                        <input type="radio" id="4x4" name="board-size" value="4" required/>
                        <label for="4x4">4x4</label>
                    </div>
                    <div class="my-button game-btn">
                        <input type="radio" id="6x6" name="board-size" value="6" required/>
                        <label for="6x6">6x6</label>
                    </div>
                </div>
                <button type="submit" class="btn">Create Room</button>
            </form>
        </section>
    </main>
{% endblock %}

game/templates/game/join_room.html
{% extends 'base.html' %}

{% block styles %}
    <style>
        main {
            display: flex;
            justify-content: center;
        }

        section {
            display: flex;
            flex-direction: column;
            text-align: center;
            gap: 10px;
            width: 50%;
        }
    </style>
{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block main %}
    <main>
        <section>
            {% if error %}
                <div class="alert alert-danger" role="alert">{{ error }}</div>
            {% endif %}

            <form method="POST">
                {% csrf_token %}
                <input name="room_id" type="text" required placeholder="Enter room name...">
                <button class="btn">Join</button>
            </form>
        </section>
    </main>
{% endblock %}

game/templates/game/pve-room.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <style>
        #room-name {
            z-index: 60;
        }

        main {
            display: flex;
            justify-content: center;
            flex-direction: column;
            align-items: center;
        }

        section {
            display: flex;
            flex-direction: column;
            align-items: center;
            text-align: center;
            gap: 10px;
            width: 50%;
        }

        #game-section {
            display: flex;
        }

        #pending-section {
            display: flex;
        }

        .btn-cancel {
            background-color: #D02424;
            width: 100%;
            cursor: pointer;
        }

        .btn:hover {
            color: white;
            background-color: #a61b1b;
            transition: ease-in-out 0.3s;
        }

        .overlay {
            visibility: hidden;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 150vh;
            background: rgba(0,0,0,0.5);
            z-index: 50;
        }

        /* Mobile styles */
        @media (max-width: 600px) {
            body {
                font-size: 12px;
            }

            .text-big {
                font-size: 6rem;
            }

            .btn-wrapper {
                width: 100%;
            }
        }

        /* Tablet styles */
        @media (min-width: 601px) and (max-width: 900px) {
            body {
                font-size: 14px;
            }

            .text-big {
                font-size: 8rem;
            }

            .btn-wrapper {
                width: 100%;
            }
        }
    </style>
    <link rel="stylesheet" href="{% static 'css/board_style.css' %}">
{% endblock %}

{% block main %}
    <main>
        <h1 id="room-name">Room name: {{ room_id }}</h1>

        <section id="profiles">
            <div class="profile" id="host">
                <div class="online" id="host-online"></div>
                <img src="{{ user.avatar.url }}" id="host-avatar" alt="host-avatar" width="75px" height="75px">
                <div class="username" id="host-username">{{ user.username }}</div>
            </div>

            <div class="profile" id="guest" dir="rtl">
                <div class="online" id="guest-online"></div>
                <img src="{{ bot.avatar.url }}" id="guest-avatar" alt="guest-avatar" width="75px" height="75px">
                <div dir="ltr" class="username" id="guest-username">Bot</div>
            </div>
        </section>

        <div id="score-board" class="overlay">
            <h2 id="winner"></h2>
            <a style="width: 50%" href="{% url "home" %}">
                <button class="btn btn-cancel" >&times;</button>
            </a>
        </div>

        <section id="game-section">
            <div id="dots"></div>
            <div id="lines"></div>
            <div id="squares"></div>
        </section>
    </main>
{% endblock %}

{% block scripts %}
    <script>
        let socket;
        const playerColors = {
            "@{{ user.username }}": 'host',
            "@{{ bot.username }}": 'guest',
        };
        const host = "@{{ user.username }}";
        const guest = "@{{ bot.username }}";
        const roomName = "{{ room_id }}";
        let playerTurn = host;

        // game board section
        const gameSection = document.getElementById('game-section');
        const pendingSection = document.getElementById('pending-section');
        const dots = document.getElementById('dots');
        const lines = document.getElementById('lines');
        const squares = document.getElementById('squares');
        const scoreBoard = document.getElementById('score-board');
        const winner = document.getElementById('winner');

        function initializeWebSocket() {
            socket = new WebSocket(`ws://${window.location.host}/ws/single-player-room/${roomName}/`);
            gameSection.style.display = 'flex';

            socket.onmessage = function(e) {
                const data = JSON.parse(e.data);

                if (data.type === 'game_move') {
                    updateGameBoard(data.row, data.col, data.side, data.player);

                    let complete_squares = data.squares;
                    if (complete_squares.length !== 0) {
                        for (let square of complete_squares) {
                            fillSquare(square.row, square.col, data.player);
                        }
                    }


                }

                else if (data.type === 'wrong_move') {
                    alert("Invalid Move!");
                }

                else if (data.type === 'game_over') {
                    if (data.winner === 'Draw') {
                        winner.innerText = 'Match Ends in a Draw.';
                    } else if (data.winner === host) {
                        winner.innerText = 'You won the match :)';
                    } else {
                        winner.innerText = 'You lost the match :(';
                    }

                    scoreBoard.style.visibility = 'visible';
                }
            };

            socket.onerror = function(error) {
                console.error('WebSocket error:', error);
            };

            socket.onclose = function() {
                console.log('WebSocket connection closed');
            };
        }

        function sendMove(row, col, side) {
            if (host !== playerTurn) {
                alert('its not your turn');
            }
            else if (socket.readyState === WebSocket.OPEN) {
                socket.send(JSON.stringify({
                    'action': 'make_move',
                    'row': row,
                    'col': col,
                    'side': side,
                    'player': host
                }));

            }
            else {
                console.error('WebSocket is not open. Ready state:', socket.readyState);
            }
        }

        function createGameBoard(n) {
            // dots
            for (let i = 1; i <= n; i++) {
                let rowDot = document.createElement('div');
                rowDot.classList.add('row-dot');

                for (let j = 1; j <= n; j++) {
                    rowDot.appendChild(createDot());
                }
                dots.appendChild(rowDot)
            }

            // lines
            for (let i = 1; i <= n; i++) {
                let rowLine = document.createElement('div');
                rowLine.classList.add('row-line');
                let rowLineVertical = document.createElement('div');
                rowLineVertical.classList.add('row-line', 'row-vertical');

                for (let j = 1; j <= n; j++) {
                    if (i !== n) {
                        if (j !== n) {
                            rowLine.appendChild(createLine(i, j, 'top', ['line']));
                            rowLineVertical.appendChild(createLine(i, j, 'left', ['line', 'vertical']));
                        } else rowLineVertical.appendChild(createLine(i, j - 1, 'right', ['line', 'vertical']));

                    } else {
                        if (j !== n) rowLine.appendChild(createLine(i - 1, j, 'bottom', ['line']));
                    }
                }

                lines.appendChild(rowLine);
                if (i !== n) lines.appendChild(rowLineVertical);
            }

            // squares
            for (let i = 1; i < n; i++) {
                let rowSquare = document.createElement('div');
                rowSquare.classList.add('row-square');

                for (let j = 1; j < n; j++) {
                    rowSquare.appendChild(createSquare(i, j));
                }
                squares.appendChild(rowSquare)
            }
        }

        function createDot() {
            const dot = document.createElement('div');
            dot.classList.add('dot');
            return dot;
        }

        function createLine(row, col, side, classList) {
            const line = document.createElement('div');
            line.classList.add(...classList);
            line.setAttribute('data-row', row);
            line.setAttribute('data-col', col);
            line.setAttribute('data-side', side);
            line.addEventListener('click', () => sendMove(row, col, side));
            return line;
        }

        function createSquare(row, col) {
            const square = document.createElement('div');
            square.classList.add('square');
            square.setAttribute('data-row', row);
            square.setAttribute('data-col', col);
            return square;
        }

        function updateGameBoard(row, col, side, player) {
            document.querySelector(`[data-row="${row}"][data-col="${col}"][data-side="${side}"]`).classList.add(`${playerColors[player]}-line`);
        }

        function fillSquare(row, col, player) {
            const square = document.querySelector(`.square[data-row="${row}"][data-col="${col}"]`);
            square.classList.add(`${playerColors[player]}-square`);
        }

        // Initialize WebSocket and create the game board when the page loads
        window.onload = () => {
            createGameBoard({{ board_size }});
            initializeWebSocket();
        };
    </script>
{% endblock %}

game/templates/game/pve.html
{% extends 'base.html' %}

{% block styles %}
    <style>
        .game-btn {
            background-color: rgba(255, 255, 255, 0.1);
            border: 3px solid white;
            border-radius: 10px;
            color: white;
            width: 100%;
            margin: 0;
        }

        .game-btn:hover {
            background-color: white;
            color: #2473D0;
        }

        main {
            display: flex;
            justify-content: center;
        }

        section {
            display: flex;
            flex-direction: column;
            text-align: center;
            gap: 10px;
            width: 50%;
        }

        input {
            width: 100%;
            margin: 0;
        }

        .my-row {
            display: flex;
            gap: 10px;
        }

        .my-button {
            position: relative;
            display: flex;
            align-items: center;
            justify-content: center;
            line-height: 250%;
        }

        .my-button label,
        .my-button input {
            position: absolute;
            cursor: pointer;

            z-index: 90;
            height: 100%;
            width: 100%;
        }

        .my-button input[type="radio"] {
            opacity: 0.001;
            z-index: 100;
        }

        .my-button input[type="radio"]:checked + label {
            background-color: white;
            color: #2473D0;
        }

        .game-btn:hover {
            background-color: inherit;
            color: white;
        }


    </style>
{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block main %}
    <main>
        <section>
            <h2>Game Configuration</h2>

            <form method="POST">
                {% csrf_token %}
                <div class="my-row">
                    <p>Board</p>
                    <div class="my-button game-btn">
                        <input type="radio" id="4x4" name="board-size" value="4" required/>
                        <label for="4x4">4x4</label>
                    </div>
                    <div class="my-button game-btn">
                        <input type="radio" id="6x6" name="board-size" value="6" required/>
                        <label for="6x6">6x6</label>
                    </div>
                </div>
                <button type="submit" class="btn">Create Room</button>
            </form>
        </section>
    </main>
{% endblock %}

game/templates/game/pvp.html
{% extends 'base.html' %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block styles %}
    <style>
        main {
            display: block;
            text-align: center;
        }

        .game-btn {
            background-color: rgba(255, 255, 255, 0.1);
            border: 3px solid white;
            border-radius: 10px;
            color: white;
            width: 50%;
            font-weight: bold;
            font-size: 24px;
        }

        .game-btn:hover {
            background-color: white;
            color: #2473D0;
        }
    </style>
{% endblock %}

{% block main %}
    <main>
        <section>
            <a href="{% url "game:create-room" %}">
                <button class="btn game-btn">Create Room</button>
            </a>
            <a href="{% url "game:join-room" %}">
                <button class="btn game-btn">Join Room</button>
            </a>
        </section>
    </main>
{% endblock %}